APP_TITLE = "Inkome"
NUMBER_OF_SYMBOLS = "Брой символи:"
NUMBER_OF_PAGES = "Брой страници:"
DROPDOWN_OPTIONS = [NUMBER_OF_SYMBOLS, NUMBER_OF_PAGES]
RATE_PER_PAGE_LABEL = "Цена на страница (лв.):"
DEDUCTION_LABEL = "Удръжки (%):"
CALCULATE_BUTTON_TEXT = "Изчисли хонорар"
FEE_INDICATOR_LABEL = "Хонорар:"
INVALID_INPUT_MESSAGE = 'Моля, въведете числови стойности в полетата "Брой символи", "Цена на страница" и "Удръжки (%)"!'
INVALID_INPUT_MESSAGE_TITLE = "Невалидна стойност"
SYMBOLS_PER_PAGE = 1800
EUR_TO_BGN = 0.511292
DEFAULT_DEDUCTION_RATE = "6"
FEE_VALUE = "{lev_value} лв. / € {euro_value}"
